# Generated by Django 4.2 on 2023-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
